export const weatherImages = {
    'Partly cloudy': require('../assets/images/partly-cloudy.png'),
    'Moderate rain': require('../assets/images/rain.png'),
    'Patchy rain possible': require('../assets/images/rain.png'),
    'Sunny': require('../assets/images/sunny.png'),
    'Clear': require('../assets/images/sunny.png'),
    'Overcast': require('../assets/images/cloudy.png'),
    'Cloudy': require('../assets/images/cloudy.png'),
    'Light rain shower': require('../assets/images/rain.png'),
    'Moderate rain at times': require('../assets/images/rain.png'),
    'Heavy rain': require('../assets/images/rain.png'),
    'Moderate or heavy rain shower': require('../assets/images/rain.png'),
    'Moderate or heavy rain with thunder': require('../assets/images/rain.png'),
    'Moderate or heavy freezing rain': require('../assets/images/rain.png'),
    'other': require('../assets/images/cloudy.png'),
};